version: "3.9"

services:
  django-backend:
    build:
      context: ./django
    volumes:
      - ./django:/django
    container_name: django-backend
    ports:
      - 8000:8000

  vue-frontend:
    build:
      context: ./vue
    volumes:
      - ./vue:/vue
    container_name: vue-frontend
    ports:
      - 80:80

  postgreSQL:
    image: postgres:13-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgresql
    ports:
      - 5432:543
volumes:
  postgres-data:
