version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672

  django-backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./django/dockerfile
    volumes:
      - ./django:/django
    ports:
      - 8000:8000
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done;
      cd django;
      celery -A rest-api.tasks worker -D;
      python3 manage.py migrate;
      python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - rabbitmq

  vue-frontend:
    platform: linux/amd64
    build:
      context: ./vue
    volumes:
      - ./vue:/vue
    ports:
      - 80:80
volumes:
  postgres-data:
