site_name: PlantMap Documentation
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
nav:
  - Home: index.md
  - Definitions: definitions.md
  - Common Errors: errors.md
theme:
  name: material
  language: en
  logo: /imgs/logo_small_color.svg
  favicon: /imgs/logo_small_color.svg
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
