site_name: PlantMap Digital Logbook
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
edit_uri: edit/main/docs/
nav:
  - Home:
      - Introduction: index.md
      - Data Flow: data-flow.md
  - Getting started:
      - Installation: "getting-started/installation.md"
      - Tutorials: "getting-started/tutorials.md"
      - Common errors: "getting-started/errors.md"
      - Improvements: "getting-started/improvements.md"
      - License: "getting-started/license.md"
  - Reference:
      - REST-API:
          - Authentication: "reference/authentication.md"
          - Beds & Plants: "reference/bed-plant-endpoints.md"
          - Company & Gardens: "reference/company-garden-endpoints.md"
          - Permission System: "reference/permissions.md"
      - Env Variables: "reference/env-vars.md"
      - Architecture: "reference/architecture.md"
      - Terminology: "reference/terminology.md"
theme:
  name: material
  language: en
  logo: imgs/logo_small_color.svg
  favicon: imgs/logo_small_color.svg
  palette:
    - scheme: naturerobots
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.instant
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.striphtml:
      strip_comments: true #default
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
plugins:
  - glightbox
