site_name: PlantMap Documentation
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
nav:
  - Home: index.md
  - Getting started:
      - Installtion: installation.md
      - Common errors: errors.md
      - License: license.md
  - Reference:
      - Definitions: definitions.md
      - Authentication: authentication.md
      - Vite Env Variables and Modes: vite-env-vars-modes.md
theme:
  name: material
  language: en
  logo: imgs/logo_small_color.svg
  favicon: imgs/logo_small_color.svg
  palette:
    - scheme: naturerobots
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.striphtml:
      strip_comments: true #default
