site_name: PlantMap Documentation
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
nav:
  - Home: index.md
  - Getting started:
      - Installation: "getting-started/installation.md"
      - Tutorials: "getting-started/tutorials.md"
      - Common errors: "getting-started/errors.md"
      - Improvements: "getting-started/improvements.md"
      - License: "getting-started/license.md"
  - Reference:
      - REST-API:
          - Authentication: "reference/authentication.md"
          - Beds & Plants: "reference/bed-plant-endpoints.md"
          - Company & Gardens: "reference/company-garden-endpoints.md"
          - Permission System: "reference/permissions.md"
      - Env Variables: "reference/env-vars.md"
      - Architecture: "reference/architecture.md"
      - Definitions: "reference/definitions.md"
theme:
  name: material
  language: en
  logo: imgs/logo_small_color.svg
  favicon: imgs/logo_small_color.svg
  palette:
    - scheme: naturerobots
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.striphtml:
      strip_comments: true #default
