site_name: PlantMap
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
nav:
  - Home: index.md
  - Getting started:
      - Installtion: installation.md
      - Common errors: errors.md
  - Reference:
      - Definitions: definitions.md
theme:
  name: material
  language: en
  logo: /imgs/logo_small_color.svg
  favicon: /imgs/logo_small_color.svg
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
