site_name: PlantMap Documentation
repo_url: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022
nav:
  - Home: index.md
  - Technical Terms: terms.md
  - Common Errors: errors.md
theme:
  name: material
  language: en
  features:
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
