FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends -y \
    bash-completion \
    build-essential \
        curl \
        git \
        sudo \
        ssh \
        vim \
        gcc \
        python3-pip \
        python3-dev \
        python3-tk \
        libssl-dev \
        libffi-dev \
        libpq-dev \
        gpg \
        && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends \
    ruby shellcheck \
    clang-format-10 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install pre-commit


# ####################################################
# # Install django
# ####################################################
# RUN pip3 install \
#         django==4.0.1\
#         djangorestframework==3.13.1 \
#         django-cors-headers==3.12.0 \
#         django-oauth-toolkit==2.0.0\
#         psycopg2-binary==2.9.3 \
#         tzdata==2022.1 \
#         celery==5.2.6 \
#         Pillow==9.1.1

# ####################################################
# # Install python gRPC
# ####################################################
# RUN pip3 install \
#         grpcio==1.46.1 \
#         grpcio-tools==1.46.1


####################################################
# Install requirements.txt
####################################################

COPY django/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

####################################################
# Install npm 14.x
####################################################
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
        && apt-get update -qq && apt-get -qq install --no-install-recommends -y nodejs \
        && rm -rf /var/lib/apt/lists/*

####################################################
# Install frontend dependencies
####################################################
RUN npm install -g create-vue

####################################################
# Install Mk-Docs
####################################################
RUN pip3 install mkdocs mkdocs-material

RUN useradd -u 1001 --create-home --shell /bin/bash docker && echo "docker:docker" | chpasswd && adduser docker sudo

RUN mkdir -p /home/docker/.vscode-server/extensions \
    && chown -R docker /home/docker/.vscode-server \
    && mkdir -p /PlantMap \
    && chown -R docker /PlantMap

USER docker

ENTRYPOINT [ "/bin/sh", "-c", "while sleep 1000; do :; done" ]
