# Generated by Django 4.0.1 on 2022-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Garden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('companies', models.ManyToManyField(to='restapi.Company')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='gardens',
            field=models.ManyToManyField(to='restapi.Garden'),
        ),
    ]
