# Generated by Django 4.0.1 on 2022-08-10 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('image_path', models.CharField(max_length=100, null=True)),
                (
                    'company',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.company'),
                ),
            ],
            options={
                'db_table': 'Garden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Widget',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GardenPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=1)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GardenPermission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                (
                    'garden',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='garden_coordinates',
                        to='restapi.garden',
                    ),
                ),
            ],
            options={
                'db_table': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CompanyPermission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=32, null=True)),
                (
                    'garden',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.garden'),
                ),
            ],
            options={
                'db_table': 'Bed',
                'managed': True,
            },
        ),
    ]
