# Generated by Django 4.0.1 on 2022-06-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gardens',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.user'),
        ),
        migrations.AddField(
            model_name='garden',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.company'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                (
                    'garden',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.garden'),
                ),
            ],
        ),
    ]
