# Generated by Django 4.0.1 on 2022-08-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinate',
            table='Coordinates',
        ),
        migrations.AlterModelTable(
            name='image',
            table='Image',
        ),
    ]
