# Generated by Django 4.0.1 on 2022-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_company_gardens_remove_user_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='uuid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
