# Generated by Django 4.0.1 on 2022-08-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_coordinate_table_alter_image_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
