# Generated by Django 4.0.1 on 2022-08-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='garden',
        ),
    ]
