# Generated by Django 4.0.1 on 2022-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_company_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.ImageField(null=True, upload_to='garden-images/e47f59b8086f4aabb6bbecb96574bf90.png'),
        ),
    ]
