# Generated by Django 4.0.1 on 2022-07-25 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0007_alter_garden_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.ImageField(null=True, upload_to='garden-images/f99bda14460d4ca8a5774611499036e0.png'),
        ),
        migrations.CreateModel(
            name='GardenPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=1, null=True)),
                (
                    'garden',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.garden'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'db_table': 'GardenPermission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=1, null=True)),
                (
                    'company',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.company'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'db_table': 'CompanyPermission',
                'managed': True,
            },
        ),
    ]
