# Generated by Django 4.0.1 on 2022-07-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_image_alter_garden_image_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='image',
        ),
        migrations.AddField(
            model_name='garden',
            name='image_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.garden'),
        ),
    ]
