# Generated by Django 4.0.1 on 2022-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_remove_coordinate_image_coordinate_garden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='id',
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
