FROM python:3.8.13-slim

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /django
COPY django /django

RUN python3 -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r django/requirements.txt && \
    adduser --disabled-password --no-create-home docker

ENV PATH="/py/bin:$PATH"

RUN mkdir -p build/gRPC
COPY protobuf-msgs build/gRPC

RUN python3 -m grpc_tools.protoc \
        --proto_path=build/gRPC \
        --python_out=build/gRPC \
        --grpc_python_out=build/gRPC \
        build/gRPC/*.proto

EXPOSE 8000

USER docker
